# Generated by Django 3.0.1 on 2019-12-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191222_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='product-1'),
            preserve_default=False,
        ),
    ]
